### ISSUE TITLE
Install using only the Ryzen 5 5600G integrated video?

### ISSUE THREAD

**Issue by tiagocaus** [alfinauzikri/B550-5600G-6600XT-Hackintosh#1]
Is it possible to install hackintosh only on the integrated graphics card of the Ryzen 5 5600G?

**Comment by alfinauzikri** [comment]
@tiagocaus It is impossible to install relying solely on the integrated graphics that are already available on AMD processors.

In order to run smoothly and properly, a compatible graphics card or internal graphics is required as in some of the previous processors produced by Intel.
